### ISSUE TITLE
Decide for a Kalman filter approach to use for BLMC robots

### ISSUE THREAD

**Issue by ahmadgazar** [machines-in-motion/mim_estimation#6]
**Note:**
For rendering github equations with MathJax please install either [mathjax github plugin for firefox](https://github.com/traversaro/github-mathjax-firefox/releases/download/v0.2.3/github_with_mathjax-0.2.3.xpi) or [mathjax github plugin for chrome](https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima)

This issue is part of this [epic](https://github.com/machines-in-motion/robot_estimation/issues/5) that aims to settle for a unified design of a generic KF for BLMC robots. 

## Goal:
The aim of this issue is to decide for the following approaches (others can also add more references) mentioned before by @nrotella to decide between for estimation on BLMC robots. I am Quoting him here:

"After thinking a little more, I actually think that for point contacts, the Pronto approach may perform better (especially because quadrupeds typically need to deal with a lot more foot slippage) and be easier to implement. Here is a very basic history of legged odometric estimators and their differences, in order:
 
1. In [Bloesch et al 2012](https://infoscience.epfl.ch/record/181040/files/Bloesch-Siegwart_State__IMU_2012.pdf) a point foot filter which integrated IMU and leg odometry was introduced. It explicitly included foot position in the EKF state and add/dropped measurements from the EKF update based on foot contact states.
2. In [Bloesch et al 2013](https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/75852/eth-7743-01.pdf) the same filter was modified to remove the foot position states from the EKF and instead use the contact constraint over a short dt to compute a base velocity measurement instead. This simplified the filter implementation and allowed adding a validation gate on the velocity measurement to reject measurements from slipping feet.
3. In [Rotella et al 2014](https://arxiv.org/pdf/1402.5450.pdf) we extended Bloesch et al 2012 to explicitly include foot orientation measurements for the humanoid flat feet. In retrospect we may have wanted to start from Bloesch et al 2013 and eliminate the foot position/orientation states from the filter entirely but this wasn't published when we started, and it seemed less relevant for a humanoid which makes pretty stable contacts.
4. In [Fallon et al 2014](https://www.research.ed.ac.uk/portal/files/18903340/14_fallon_humanoids.pdf) essentially the same filter from Bloesch et al 2013 was extended to include LIDAR corrections for absolute base pose drift. Since Atlas has a really high precision gyroscope, they didn't care about including foot orientation measurements for base orientation corrections, so it's the same as a point foot filter.
5. Skipping ahead some years, [Pronto](https://www.robots.ox.ac.uk/~mobile/drs/Papers/2020FRONTIERS_camurri.pdf) derives from Fallon et al 2014 but includes visual odometry as well, however the kinematic filter at the core is basically the same. They include another previous work from Camurri et al 2017 which adds contact estimation too which is nice. But fundamentally, the quadruped kinematic filter is the same as Bloesch et al 2013.

 Overall I think for a quadruped like Solo and even a humanoid like Bolt, both of which are very dynamic and make lots of frequent, unstable contacts, it makes more sense to go with something based on Bloesch et al 2013. This basically means the foot positions are not included explicitly in the filter, and instead get used to compute a base velocity measurement. For humanoids, as Pronto shows, you can do the same thing and forget including foot orientations or measurements (especially with a good IMU like the one on Atlas; with a cheaper IMU this might not be true). If we're basically starting from scratch anyway, I think for a robot like Solo it makes more sense to implement this slightly different EKF. "

**Comment by ahmadgazar** [comment]
I agree as well on using [Bloesch et al 2013](https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/75852/eth-7743-01.pdf). It's a UKF however, which I believe will work even better. I am also ok with implementing the two versions as well.

**Comment by MaximilienNaveau** [comment]
If you agree let's start with this one.
If we feel bored we can implement 2 of them, but let's start with one ^^

**Comment by nrotella** [comment]
> I agree as well on using [Bloesch et al 2013](https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/75852/eth-7743-01.pdf). It's a UKF however, which I believe will work even better. I am also ok with implementing the two versions as well.

Thank you for creating this issue. I agree we should implement one of these methods which has been shown to work well on a quadruped, I feel the results will be better than with the humanoid filter from my paper. Interestingly the papers which follow Bloesch et al 2013 (Fallon et al 2014 and Pronto) go back to using an EKF instead of a UKF. Bloesch et al 2013 describes the choice as follows:

![image](https://user-images.githubusercontent.com/11082677/104052861-ef3fe200-51af-11eb-8b17-d1c5e528f3d1.png)

however this is a very technical motivation and I'm sure an EKF would work fine as well. I wonder if Fallon et al chose to use an EKF because it's more efficient or just because most people seem more comfortable with EKF than UKF (myself included). I think either way can work, whatever is fastest for prototyping in python makes sense.

I actually wrote C++ EKF and UKF template classes which I used for some later papers, perhaps they're useful after prototyping in python: https://gitlab.is.tue.mpg.de/amd-clmc/humanoid_control/-/tree/master/filtering_tools/template/include/kalman_filter_templates I also remember Manuel Wuthrich was working on some generic filtering library at MPI, I wonder what happened with that?

**Comment by ahmadgazar** [comment]
> I wonder if Fallon et al chose to use an EKF because it's more efficient or just because most people seem more comfortable with EKF than UKF (myself included).

I think speed is one reason, and also tuning parameters of the sigma points can sometimes be a cumbersome may be. 

>  also remember Manuel Wuthrich was working on some generic filtering library at MPI, I wonder what happened with that?

yea, but I think that's for fixed base manipulators though.

**Comment by ahmadgazar** [comment]
I skimmed through the latest version of [Pronto](https://github.com/machines-in-motion/mim_estimation/files/5789205/pronto.pdf), and I think the notation there is pretty neat. One evident thing I noticed different from Bloesch papers is that the velocities are described in the base frame and not in the world frame, and they don't incorporate IMU information during discretization of the base position.

**Comment by nrotella** [comment]
> I skimmed through the latest version of [Pronto](https://github.com/machines-in-motion/mim_estimation/files/5789205/pronto.pdf), and I think the notation there is pretty neat. One evident thing I noticed different from Bloesch papers is that the velocities are described in the base frame and not in the world frame, and they don't incorporate IMU information during discretization of the base position.

Thank you for sharing the paper, it's a nice one. Bloesch et al actually introduced these "robot centric" coordinates in the 2013 paper, which Fallon based his 2014 paper and then Pronto on. I think the reason for expressing base velocity in base frame is because they measure this velocity per leg in contact, so it complicates the process model a little to simplify the measurement model I guess.

What do you mean by "they don't incorporate IMU information during discretization of the base position" ? This part I'm not sure about.

I know @MaximilienNaveau had mentioned there was a possibility to use Pronto for Solo, if this is still a consideration then maybe this example for [Pronto on ANYmal](https://github.com/ori-drs/pronto_anymal_example) would help. I understand the concern is that Solo has no perception, so unless Pronto allows to use only the kinematic model (which doesn't seem to be possible but I haven't looked much at the Github repo) then it's not worth pursuing. I think to get decent long-term base estimation on Solo you will eventually need to add at least stereo vision, though.

**Comment by ahmadgazar** [comment]
> What do you mean by "they don't incorporate IMU information during discretization of the base position" ?

Sorry, may be I expressed this in a confusing way. I mean the IMU acceleration is used during integrating of the base velocity (first-order information), but not used as well as second-order information for integrating the base position. So if we assume **robot-centric coordinates** (i.e. quantities expressed in the base frame), and **zero-order hold on IMU data**,  Pronto integrates the base position and velocity using first-order integration as 

\begin{align} \tag{1}
r^-_{k+1} = r^+_{k} + \Delta t v^+_{k} , \newline
v^-_{k+1} = (- \omega^\tilde_k v_k + (R_{k-1})^T g + a_k) \Delta t
\end{align}

while  Bloesch and @nrotella (regardless of the different convention) uses second-order info for integrating base position (to incorporate IMU acceleration as well) and first-order integration for base velocity as follows:   

\begin{align} \tag{2}
r^-_{k+1} = r^+_{k} + \Delta t v^+_{k} + \frac{\Delta t^2}{2}(R_{k-1})^T g + a_k), \newline 
v^-_{k+1} = (- \omega^\tilde_k v_k + (R_{k-1})^T g + a_k) \Delta t
\end{align}
$a_k$ is the proper acceleration, $R$ is the rotation matrix from base to world, $g$ is the gravity vector, and $^{-/+}$ represents prior/posterior quantities respectively. 

In the end, using second-order integration will lead to more accurate base positions, but may be it was not so evident in their case with ANYmal. I just wanted to confirm if my observation is correct, and to decide what is beneficial in the end in practice.

**Comment by ahmadgazar** [comment]
> I understand the concern is that Solo has no perception, so unless Pronto allows to use only the kinematic model (which doesn't seem to be possible but I haven't looked much at the Github repo) then it's not worth pursuing. I think to get decent long-term base position estimation on Solo you will eventually need to add at least stereo vision, though. If you care mainly about base velocity then I think a kinematic-only approach is valid for now.

I think for now there is no plan to include perception on Solo, and if that will be the case in the future, it might make sense to import Pronto. My opinion out of the above choices is to proceed with an EKF/UKF versions based on Bloesch 2013 since the rest of the recent papers build on top of it. Do we all agree on this?

**Comment by MaximilienNaveau** [comment]
@nrotella the template ekf/ukf you did, I think the code is already inside this repo:
https://github.com/machines-in-motion/mim_estimation/tree/master/include/mim_estimation/filtering_tools

Let me know if this is the one you thought about.

**Comment by nrotella** [comment]
> @nrotella the template ekf/ukf you did, I think the code is already inside this repo:
> https://github.com/machines-in-motion/mim_estimation/tree/master/include/mim_estimation/filtering_tools
> 
> Let me know if this is the one you thought about.

Yes that's the one, it may be useful here when moving to C++, thanks for finding it. It is general enough to be used for any estimation problem which you can describe through state and measurement classes I believe.

**Comment by ahmadgazar** [comment]
Ok, great. I think we can as well close this issue, and proceed with deciding for the mathematical notation of Bloesch 2013 in this [issue](https://github.com/machines-in-motion/mim_estimation/issues/7).

**Comment by nrotella** [comment]
> Ok, great. I think we can as well close this issue, and proceed with deciding for the mathematical notation of Bloesch 2013 in this [issue](https://github.com/machines-in-motion/mim_estimation/issues/7).

I wanted to add that I agree with the approach based on Bloesch 2013, however that paper in particular has some unnecessarily complicated notation in my opinion so it may be easier to follow Fallon 2014 or the Pronto paper (just the kinematic portions, ignoring the perception measurements). Either way, the approach is roughly the same, and differs from my paper (Rotella 2014) in that it robustifies the filter by removing explicit foot position states and ignoring foot orientation entirely. We can discuss in another issue how to move forward.
