### ISSUE TITLE
Decide for the mathematical notation and add the technical report of the KF

### ISSUE THREAD

**Issue by ahmadgazar** [machines-in-motion/mim_estimation#7]
**Note:**
For rendering github equations with MathJax please install either [mathjax github plugin for firefox](https://github.com/traversaro/github-mathjax-firefox/releases/download/v0.2.3/github_with_mathjax-0.2.3.xpi) or [mathjax github plugin for chrome](https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima)

This issue is part of this [epic](https://github.com/machines-in-motion/robot_estimation/issues/5) that aims to settle for a unified design of a generic KF for BLMC robots. 

## Goal:
The aim of this issue is to discuss the mathematical notation and write a detailed report later for the filter derivation with reference to the code.

**Comment by ahmadgazar** [comment]
Sorry, I was busy the last days on updating this issue. Based on this [issue](https://github.com/machines-in-motion/mim_estimation/issues/6), we agreed to follow the approach of [Bloesch et. all 2013](https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/75852/eth-7743-01.pdf), which adapts a **robot-centric** convention (i.e. quantities are expressed in the robot's body frame), and drops foot step locations from the filter state. We will start first by developing a prototype EKF version of it, then proceed with it's UKF version.

Regarding the mathematical notation, I think we might agree that the notation in [Bloesch et. all 2013](https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/75852/eth-7743-01.pdf) is a bit heavy, and so I will be adapting the notation from [Pronto](https://github.com/machines-in-motion/mim_estimation/files/5789205/pronto.pdf) (only the kinematic portions that concerns us).  

## Frames:
![Screenshot from 2021-01-13 19-36-29](https://user-images.githubusercontent.com/15094592/104598329-bce22900-5676-11eb-892f-f001d16b0c44.png)

The above frame depiction is taken from [Pronto](https://github.com/machines-in-motion/mim_estimation/files/5789205/pronto.pdf). We are mainly concerned about 4 main frames of interest, which I will refer to them with a calligraphic notation as follows to avoid confusion in the equations notation later:

$\mathcal{W}:$ World frame
$\mathcal{B}:$ Base frame
$\mathcal{I}:$ IMU frame 
$\mathcal{K}\_{xx}$ Ankle frame, where $\_{xx}$ is the specific initials for each foot 

We drop the rest of frames since we won't include a camera or a LIDAR.

## Notation:
$^{B}\mathbf{R}_\mathcal{W} \in$ SO(3): Rotation matrix representing the base orientation from the world frame to base frame
$\mathbf{q}  \in so(3)$: base quaternion corresponding to  $^{B}\mathbf{R}_\mathcal{W}$
$^{B}\mathbf{P}\_{\mathcal{W} \mathcal{B}} \in \mathbb{R}^3$: Base position from world to base expressed in the base frame
$^{B}\mathbf{\omega}\_{\mathcal{W} \mathcal{B}} \in \mathbb{R}^3$: Base velocity from world to base expressed in the base frame
$^{I}\mathbf{b}^a \in \mathbb{R}^3$: accelerometer bias expressed in the IMU frame
$^{I}\mathbf{b}^\omega \in \mathbb{R}^3$: gyroscope bias expressed in the IMU frame
$\mathbf{a}_k = \mathbf{a}(t_k)$: A time dependent vector quantity $\mathbf{a}$ computed at time $t_k$

## State tuple:
The goal of the filter is to estimate the robot state defined in the following struct combining base position, velocity, orientation ,and IMU biases as follows
 
\begin{align}\tag{1}
\mathbf{x}_k = \begin{\bmatrix} \mathbf{p}_k & \mathbf{q}_k & \mathbf{v}_k &  \mathbf{b}^a_k & \mathbf{b}^\omega_k \end{\bmatrix}^T
\end{align}

## IMU transient model:
## Transient model and it's jacobian:
## Measurement model and it's jacobian:
## Prediction step:
## Update step:
TO BE CONTINUED

**Comment by ahmadgazar** [comment]
As I am checking the equations Bloesch 2013 and Pronto, I could not find the complete math, especially for the definitions of the noise and measurement jacobians. @nrotella Any ideas which source to refer to that include the complete math and adopts the same convention?

**Comment by nrotella** [comment]
These papers unfortunately don't always give the full details, ie the
Jacobians. That was a problem when I first tried to implement this, hence
why my paper gave the linearization a explicitly. I will check back to see
if I can find more details in any of them.

**Comment by ahmadgazar** [comment]
Yea, I see. Thanks. In the meanwhile, I will try to do those calculations manually and write them here to discuss if they make sense.

**Comment by nrotella** [comment]
Thanks for updating the derivations! I was about to share this appendix to my 2014 paper which walks through linearization, but maybe it's too late :) https://nrotella.github.io/download/IROS2014_linearization.pdf

I will take a look at your updated comment.

**Comment by ahmadgazar** [comment]
**Note:**

Arriving to the linearization equations (5a, 5b, 5c) may not seem trivial. So, I am posting here the computations I did so that whoever interested can double check them to make sure they are indeed correct for robot-centeric coordinates.

![image](https://user-images.githubusercontent.com/15094592/105484643-ee2cab80-5cab-11eb-9aff-9f2e73a495b5.png)

![image](https://user-images.githubusercontent.com/15094592/105484710-12888800-5cac-11eb-8f75-0d323851e189.png)

![image](https://user-images.githubusercontent.com/15094592/105484809-3f3c9f80-5cac-11eb-9a48-e12fc70cc89a.png)

![image](https://user-images.githubusercontent.com/15094592/105484853-4e235200-5cac-11eb-9a6a-e6b3a6bf0158.png)

Agaig, you can check @nrotella 's linearization notes as guideline and refer to the [excellent report by Joan Sola](https://www.iri.upc.edu/people/jsola/JoanSola/objectes/notes/kinematics.pdf#subsubsection.3.1.1) for further details, but I think the above notes should be sufficient to get you there.

**Comment by ahmadgazar** [comment]
I am also posting how to arrive to the linearized measurement model (equation 14).
![image](https://user-images.githubusercontent.com/15094592/105493180-52a23780-5cb9-11eb-9565-713b9695f147.png)

 @nrotella Do you think we can ignore the last term ($-[\mathbf{p}_i]\_{\times} \boldsymbol{\eta}\_{omega}$) since it can be seen as part of the collected measurement additive uncertainties $\boldsymbol{\eta}_v$ ?

**Comment by ahmadgazar** [comment]
Unless nobody has objections on the above notation and math, then I will be adapting the implementation of the EKF class based on the above formulation. Feel free to reopen if you catch any errors or have any suggestions. @nrotella @MaximilienNaveau @jviereck @majidkhadiv

**Comment by nrotella** [comment]
Hi Ahmad, I apologise, I had less time this past week than expected so I
didn't get the chance to look over your math in detail. I will let you know
if I find anything that looks incorrect when I get the chance, but for now
I think it's a good idea to start the implementation.

**Comment by ahmadgazar** [comment]
It's ok, no worries, whenever you have time :)).

**Comment by nrotella** [comment]
I just derived the linearized process equations myself and arrived at the same results as you show in equations 5a through 5e :) One thing that tripped me up at first in your derivations for linearized velocity and orientation derivatives is that in your notes, you state in one place that $R\approx \bar{R}(I+\phi^{\times})$ which is correct, but in another place that $R\approx (I-\phi^{\times})\bar{R}$ which is only correct for the JPL convention as I used in [my notes](https://nrotella.github.io/download/IROS2014_linearization.pdf); in our case, the latter is the small angle approximation of $R^{T}$ instead. This stuff gets very tricky.

I also wondered if we could easily verify these derivations against the open-source Pronto library and found what I believe to be the [process Jacobian code](https://github.com/ori-drs/pronto/blob/master/pronto_core/src/rbis.cpp#L13-L36), and the matrix entries there agree with what we've derived here. 

I need to double-check the measurement linearization next and see if I can find the corresponding Jacobian in Pronto to verify it.

**Comment by nrotella** [comment]
I found the [noise Jacobian](https://github.com/ori-drs/pronto/blob/master/pronto_core/src/rbis.cpp#L125-L135) in Pronto but interestingly it looks like there are a few sign differences in their implementation compared to the results above? Not sure how that's the case; I got the same results as you for $L_{c}$ @ahmadgazar (in Pronto they call it "Wc").

**Comment by nrotella** [comment]
> @nrotella Do you think we can ignore the last term ($-[\mathbf{p}_i]_{\times} \boldsymbol{\eta}_{\omega}$) since it can be seen as part of the collected measurement additive uncertainties $\boldsymbol{\eta}_v$ ?

I think this can be ignored in the EKF; Bloesch et al 2013 used a UKF for this reason apparently, but I doubt the effect of dropping this term is significant:

![image](https://user-images.githubusercontent.com/11082677/105801091-fdd31b00-5f5d-11eb-919b-71fcdf15fffd.png)

**Comment by nrotella** [comment]
I'm also a little confused about how the measurement itself:

![image](https://user-images.githubusercontent.com/11082677/105801668-3fb09100-5f5f-11eb-9a39-5fa2e04308a9.png)

is derived, even before trying to linearize it. Then, in your linearization, you expand the first velocity term on the right (which is the velocity of the foot, no?) as if it's the velocity of the base. Maybe I'm missing something here; I know this comes from the Pronto paper but I'm confused how they derived it there as well.

Also I can't seem to find this kinematic measurement in their codebase :( They have a pretty complex [measurement update interface](https://github.com/ori-drs/pronto/blob/master/pronto_core/src/rbis_update_interface.cpp) which handles a bunch of different types of measurements, and I can't find the quadruped-specific code.

**Comment by ahmadgazar** [comment]
Hi @nrotella. Thanks for checking the derivations. 

> One thing that tripped me up at first in your derivations for linearized velocity and orientation derivatives is that in your notes, you state in one place that $R\approx \bar{R}(I+\phi^{\times})$ which is correct, but in another place that $R\approx (I-\phi^{\times})\bar{R}$ which is only correct for the JPL convention as I used in [my notes](https://nrotella.github.io/download/IROS2014_linearization.pdf); in our case, the latter is the small angle approximation of $R^{T}$ instead. This stuff gets very tricky.

Yes, that's a typo actually.

> I found the [noise Jacobian](https://github.com/ori-drs/pronto/blob/master/pronto_core/src/rbis.cpp#L125-L135) in Pronto but interestingly it looks like there are a few sign differences in their implementation compared to the results above? Not sure how that's the case; I got the same results as you for $L_{c}$ @ahmadgazar (in Pronto they call it "Wc").

I didn't check their code base, but I believe our derivation should be correct.

> I think this can be ignored in the EKF; Bloesch et al 2013 used a UKF for this reason apparently, but I doubt the effect of dropping this term is significant.

I also thought so.

> I'm also a little confused about how the measurement itself:
> 
> ![image](https://user-images.githubusercontent.com/11082677/105801668-3fb09100-5f5f-11eb-9a39-5fa2e04308a9.png)
> 
> is derived, even before trying to linearize it. 

I think it should be derived as follows:
![IMG_0082](https://user-images.githubusercontent.com/15094592/105988854-92de2d00-60a0-11eb-8956-45e79a9a2458.jpg)

> 
Then, in your linearization, you expand the first velocity term on the right (which is the velocity of the foot, no?) as if it's the velocity of the base. 

You are right indeed, I confused the base velocity with the foot velocity. I should update this, and the jacobian accordingly.

**Comment by nrotella** [comment]
Thanks for the derivation of the measurement equation; I got stuck because
I forgot you can flip the sign of the velocity to change the order of the
frames (eg velocity of world rel to base is negative of base rel to world,
both wrt same frame). I think it's still slightly off because the term you
circled as the "total base linear velocity" has the form
$v+r\times \omega$ rather than $v+\omega\times r$, so there's a minus sign
unaccounted for somewhere. Anyway, it's close enough, thanks for working
through it.

If you remove the velocity from the linearization, though, then you only
end up with the measurement depending on the gyro bias... This feels wrong
to me, since it means the only way for information to propagate through the
rest of the states is via this bias term, no? But I still don't think
expanding the foot velocity as if it's the base makes sense either. I'll
try to take a closer look later.

One thing to try, which is definitely worth doing no matter what, is to
compute th se Jacobians numerically once you have the nonlinear equations
implemented. Then you can easily check our derivations against the
numerical results, I used to do this a lot and it helped reveal errors.

**Comment by ahmadgazar** [comment]
> If you remove the velocity from the linearization, though, then you only
> end up with the measurement depending on the gyro bias... This feels wrong
> to me, since it means the only way for information to propagate through the
> rest of the states is via this bias term, no? But I still don't think
> expanding the foot velocity as if it's the base makes sense either. I'll
> try to take a closer look later.

I agree that there is something fishy there for me as well. I am also kind of confused now with new model between the predicted measurements and the observed ones. I guess in this case the predicted measurements shall come from numerical differentiation of the feet positions? 

![image](https://user-images.githubusercontent.com/15094592/106028724-9687a900-60cc-11eb-860a-6bf38cf967e0.png)

> One thing to try, which is definitely worth doing no matter what, is to
> compute th se Jacobians numerically once you have the nonlinear equations
> implemented. Then you can easily check our derivations against the
> numerical results, I used to do this a lot and it helped reveal errors

yea, currently working on that unit test actually.

**Comment by ahmadgazar** [comment]
Based on the discussion in this [PR](https://github.com/machines-in-motion/mim_estimation/pull/8#discussion_r584304913), on the measurement jacobian. This issue can be closed.
